# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Pack extension

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Install gnome-shell
      run: sudo apt update && sudo apt install -y gnome-shell gettext
      
    - name: Pack extension
      run: gnome-extensions pack --podir=po --gettext-domain=nordvpn-quick-toggle --extra-source=asyncHandler.js --extra-source=icons src
      
    - name: Release artifacts
      uses: ncipollo/release-action@v1
      with:
        artifacts: "nordvpnquicktoggle@wedaxi.com.shell-extension.zip"
        tag: "release"

